# Change these first
owner: LunaLu-dev # Your GitHub organization or username, where this repository lives
repo: Uptime-Monitor # The name of this repository

sites:
  - name: LunaLu.org
    url: https://www.lunalu.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
